// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.11.4
// source: github.com/moby/buildkit/session/pullping/pullping.proto

package pullping

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PullPing_Pull_FullMethodName = "/moby.pullping.v1.PullPing/Pull"
)

// PullPingClient is the client API for PullPing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PullPingClient interface {
	Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullResponse], error)
}

type pullPingClient struct {
	cc grpc.ClientConnInterface
}

func NewPullPingClient(cc grpc.ClientConnInterface) PullPingClient {
	return &pullPingClient{cc}
}

func (c *pullPingClient) Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PullPing_ServiceDesc.Streams[0], PullPing_Pull_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullRequest, PullResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PullPing_PullClient = grpc.ServerStreamingClient[PullResponse]

// PullPingServer is the server API for PullPing service.
// All implementations should embed UnimplementedPullPingServer
// for forward compatibility.
type PullPingServer interface {
	Pull(*PullRequest, grpc.ServerStreamingServer[PullResponse]) error
}

// UnimplementedPullPingServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPullPingServer struct{}

func (UnimplementedPullPingServer) Pull(*PullRequest, grpc.ServerStreamingServer[PullResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Pull not implemented")
}
func (UnimplementedPullPingServer) testEmbeddedByValue() {}

// UnsafePullPingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PullPingServer will
// result in compilation errors.
type UnsafePullPingServer interface {
	mustEmbedUnimplementedPullPingServer()
}

func RegisterPullPingServer(s grpc.ServiceRegistrar, srv PullPingServer) {
	// If the following call pancis, it indicates UnimplementedPullPingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PullPing_ServiceDesc, srv)
}

func _PullPing_Pull_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PullPingServer).Pull(m, &grpc.GenericServerStream[PullRequest, PullResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PullPing_PullServer = grpc.ServerStreamingServer[PullResponse]

// PullPing_ServiceDesc is the grpc.ServiceDesc for PullPing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PullPing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moby.pullping.v1.PullPing",
	HandlerType: (*PullPingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Pull",
			Handler:       _PullPing_Pull_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "github.com/moby/buildkit/session/pullping/pullping.proto",
}
