// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.11.4
// source: github.com/moby/buildkit/session/pullping/pullping.proto

package pullping

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []string               `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	Resp          map[string]string      `protobuf:"bytes,2,rep,name=resp,proto3" json:"resp,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_github_com_moby_buildkit_session_pullping_pullping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_session_pullping_pullping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_session_pullping_pullping_proto_rawDescGZIP(), []int{0}
}

func (x *PullRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *PullRequest) GetResp() map[string]string {
	if x != nil {
		return x.Resp
	}
	return nil
}

type PullResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullResponse) Reset() {
	*x = PullResponse{}
	mi := &file_github_com_moby_buildkit_session_pullping_pullping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullResponse) ProtoMessage() {}

func (x *PullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_session_pullping_pullping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullResponse.ProtoReflect.Descriptor instead.
func (*PullResponse) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_session_pullping_pullping_proto_rawDescGZIP(), []int{1}
}

var File_github_com_moby_buildkit_session_pullping_pullping_proto protoreflect.FileDescriptor

const file_github_com_moby_buildkit_session_pullping_pullping_proto_rawDesc = "" +
	"\n" +
	"8github.com/moby/buildkit/session/pullping/pullping.proto\x12\x10moby.pullping.v1\"\x9b\x01\n" +
	"\vPullRequest\x12\x16\n" +
	"\x06images\x18\x01 \x03(\tR\x06images\x12;\n" +
	"\x04resp\x18\x02 \x03(\v2'.moby.pullping.v1.PullRequest.RespEntryR\x04resp\x1a7\n" +
	"\tRespEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0e\n" +
	"\fPullResponse2S\n" +
	"\bPullPing\x12G\n" +
	"\x04Pull\x12\x1d.moby.pullping.v1.PullRequest\x1a\x1e.moby.pullping.v1.PullResponse0\x01B+Z)github.com/moby/buildkit/session/pullpingb\x06proto3"

var (
	file_github_com_moby_buildkit_session_pullping_pullping_proto_rawDescOnce sync.Once
	file_github_com_moby_buildkit_session_pullping_pullping_proto_rawDescData []byte
)

func file_github_com_moby_buildkit_session_pullping_pullping_proto_rawDescGZIP() []byte {
	file_github_com_moby_buildkit_session_pullping_pullping_proto_rawDescOnce.Do(func() {
		file_github_com_moby_buildkit_session_pullping_pullping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_moby_buildkit_session_pullping_pullping_proto_rawDesc), len(file_github_com_moby_buildkit_session_pullping_pullping_proto_rawDesc)))
	})
	return file_github_com_moby_buildkit_session_pullping_pullping_proto_rawDescData
}

var file_github_com_moby_buildkit_session_pullping_pullping_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_moby_buildkit_session_pullping_pullping_proto_goTypes = []any{
	(*PullRequest)(nil),  // 0: moby.pullping.v1.PullRequest
	(*PullResponse)(nil), // 1: moby.pullping.v1.PullResponse
	nil,                  // 2: moby.pullping.v1.PullRequest.RespEntry
}
var file_github_com_moby_buildkit_session_pullping_pullping_proto_depIdxs = []int32{
	2, // 0: moby.pullping.v1.PullRequest.resp:type_name -> moby.pullping.v1.PullRequest.RespEntry
	0, // 1: moby.pullping.v1.PullPing.Pull:input_type -> moby.pullping.v1.PullRequest
	1, // 2: moby.pullping.v1.PullPing.Pull:output_type -> moby.pullping.v1.PullResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_moby_buildkit_session_pullping_pullping_proto_init() }
func file_github_com_moby_buildkit_session_pullping_pullping_proto_init() {
	if File_github_com_moby_buildkit_session_pullping_pullping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_moby_buildkit_session_pullping_pullping_proto_rawDesc), len(file_github_com_moby_buildkit_session_pullping_pullping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_moby_buildkit_session_pullping_pullping_proto_goTypes,
		DependencyIndexes: file_github_com_moby_buildkit_session_pullping_pullping_proto_depIdxs,
		MessageInfos:      file_github_com_moby_buildkit_session_pullping_pullping_proto_msgTypes,
	}.Build()
	File_github_com_moby_buildkit_session_pullping_pullping_proto = out.File
	file_github_com_moby_buildkit_session_pullping_pullping_proto_goTypes = nil
	file_github_com_moby_buildkit_session_pullping_pullping_proto_depIdxs = nil
}
