// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.11.4
// source: github.com/moby/buildkit/session/localhost/localhost.proto

package localhost

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutputMessage_Status int32

const (
	OutputMessage_RUNNING OutputMessage_Status = 0
	OutputMessage_DONE    OutputMessage_Status = 1
	OutputMessage_KILLED  OutputMessage_Status = 2
)

// Enum value maps for OutputMessage_Status.
var (
	OutputMessage_Status_name = map[int32]string{
		0: "RUNNING",
		1: "DONE",
		2: "KILLED",
	}
	OutputMessage_Status_value = map[string]int32{
		"RUNNING": 0,
		"DONE":    1,
		"KILLED":  2,
	}
)

func (x OutputMessage_Status) Enum() *OutputMessage_Status {
	p := new(OutputMessage_Status)
	*p = x
	return p
}

func (x OutputMessage_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputMessage_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_moby_buildkit_session_localhost_localhost_proto_enumTypes[0].Descriptor()
}

func (OutputMessage_Status) Type() protoreflect.EnumType {
	return &file_github_com_moby_buildkit_session_localhost_localhost_proto_enumTypes[0]
}

func (x OutputMessage_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputMessage_Status.Descriptor instead.
func (OutputMessage_Status) EnumDescriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_session_localhost_localhost_proto_rawDescGZIP(), []int{1, 0}
}

// InputMessage contains stdin data
type InputMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       []string               `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	Stdin         []byte                 `protobuf:"bytes,2,opt,name=stdin,proto3" json:"stdin,omitempty"`
	Dir           string                 `protobuf:"bytes,3,opt,name=dir,proto3" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputMessage) Reset() {
	*x = InputMessage{}
	mi := &file_github_com_moby_buildkit_session_localhost_localhost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputMessage) ProtoMessage() {}

func (x *InputMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_session_localhost_localhost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputMessage.ProtoReflect.Descriptor instead.
func (*InputMessage) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_session_localhost_localhost_proto_rawDescGZIP(), []int{0}
}

func (x *InputMessage) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *InputMessage) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

func (x *InputMessage) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

// OutputMessage contains stdout and stderr data
type OutputMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        []byte                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Status        OutputMessage_Status   `protobuf:"varint,3,opt,name=status,proto3,enum=moby.localhost.v1.OutputMessage_Status" json:"status,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // only valid if status is done
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputMessage) Reset() {
	*x = OutputMessage{}
	mi := &file_github_com_moby_buildkit_session_localhost_localhost_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputMessage) ProtoMessage() {}

func (x *OutputMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_session_localhost_localhost_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputMessage.ProtoReflect.Descriptor instead.
func (*OutputMessage) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_session_localhost_localhost_proto_rawDescGZIP(), []int{1}
}

func (x *OutputMessage) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *OutputMessage) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *OutputMessage) GetStatus() OutputMessage_Status {
	if x != nil {
		return x.Status
	}
	return OutputMessage_RUNNING
}

func (x *OutputMessage) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// BytesMessage contains a chunk of byte data
type BytesMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BytesMessage) Reset() {
	*x = BytesMessage{}
	mi := &file_github_com_moby_buildkit_session_localhost_localhost_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BytesMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesMessage) ProtoMessage() {}

func (x *BytesMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_session_localhost_localhost_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesMessage.ProtoReflect.Descriptor instead.
func (*BytesMessage) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_session_localhost_localhost_proto_rawDescGZIP(), []int{2}
}

func (x *BytesMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_github_com_moby_buildkit_session_localhost_localhost_proto protoreflect.FileDescriptor

const file_github_com_moby_buildkit_session_localhost_localhost_proto_rawDesc = "" +
	"\n" +
	":github.com/moby/buildkit/session/localhost/localhost.proto\x12\x11moby.localhost.v1\"P\n" +
	"\fInputMessage\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x12\x14\n" +
	"\x05stdin\x18\x02 \x01(\fR\x05stdin\x12\x10\n" +
	"\x03dir\x18\x03 \x01(\tR\x03dir\"\xca\x01\n" +
	"\rOutputMessage\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\fR\x06stderr\x12?\n" +
	"\x06status\x18\x03 \x01(\x0e2'.moby.localhost.v1.OutputMessage.StatusR\x06status\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\"+\n" +
	"\x06Status\x12\v\n" +
	"\aRUNNING\x10\x00\x12\b\n" +
	"\x04DONE\x10\x01\x12\n" +
	"\n" +
	"\x06KILLED\x10\x02\"\"\n" +
	"\fBytesMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xf4\x01\n" +
	"\tLocalhost\x12M\n" +
	"\x04Exec\x12\x1f.moby.localhost.v1.InputMessage\x1a .moby.localhost.v1.OutputMessage(\x010\x01\x12K\n" +
	"\x03Get\x12\x1f.moby.localhost.v1.BytesMessage\x1a\x1f.moby.localhost.v1.BytesMessage(\x010\x01\x12K\n" +
	"\x03Put\x12\x1f.moby.localhost.v1.BytesMessage\x1a\x1f.moby.localhost.v1.BytesMessage(\x010\x01B,Z*github.com/moby/buildkit/session/localhostb\x06proto3"

var (
	file_github_com_moby_buildkit_session_localhost_localhost_proto_rawDescOnce sync.Once
	file_github_com_moby_buildkit_session_localhost_localhost_proto_rawDescData []byte
)

func file_github_com_moby_buildkit_session_localhost_localhost_proto_rawDescGZIP() []byte {
	file_github_com_moby_buildkit_session_localhost_localhost_proto_rawDescOnce.Do(func() {
		file_github_com_moby_buildkit_session_localhost_localhost_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_moby_buildkit_session_localhost_localhost_proto_rawDesc), len(file_github_com_moby_buildkit_session_localhost_localhost_proto_rawDesc)))
	})
	return file_github_com_moby_buildkit_session_localhost_localhost_proto_rawDescData
}

var file_github_com_moby_buildkit_session_localhost_localhost_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_moby_buildkit_session_localhost_localhost_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_moby_buildkit_session_localhost_localhost_proto_goTypes = []any{
	(OutputMessage_Status)(0), // 0: moby.localhost.v1.OutputMessage.Status
	(*InputMessage)(nil),      // 1: moby.localhost.v1.InputMessage
	(*OutputMessage)(nil),     // 2: moby.localhost.v1.OutputMessage
	(*BytesMessage)(nil),      // 3: moby.localhost.v1.BytesMessage
}
var file_github_com_moby_buildkit_session_localhost_localhost_proto_depIdxs = []int32{
	0, // 0: moby.localhost.v1.OutputMessage.status:type_name -> moby.localhost.v1.OutputMessage.Status
	1, // 1: moby.localhost.v1.Localhost.Exec:input_type -> moby.localhost.v1.InputMessage
	3, // 2: moby.localhost.v1.Localhost.Get:input_type -> moby.localhost.v1.BytesMessage
	3, // 3: moby.localhost.v1.Localhost.Put:input_type -> moby.localhost.v1.BytesMessage
	2, // 4: moby.localhost.v1.Localhost.Exec:output_type -> moby.localhost.v1.OutputMessage
	3, // 5: moby.localhost.v1.Localhost.Get:output_type -> moby.localhost.v1.BytesMessage
	3, // 6: moby.localhost.v1.Localhost.Put:output_type -> moby.localhost.v1.BytesMessage
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_moby_buildkit_session_localhost_localhost_proto_init() }
func file_github_com_moby_buildkit_session_localhost_localhost_proto_init() {
	if File_github_com_moby_buildkit_session_localhost_localhost_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_moby_buildkit_session_localhost_localhost_proto_rawDesc), len(file_github_com_moby_buildkit_session_localhost_localhost_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_moby_buildkit_session_localhost_localhost_proto_goTypes,
		DependencyIndexes: file_github_com_moby_buildkit_session_localhost_localhost_proto_depIdxs,
		EnumInfos:         file_github_com_moby_buildkit_session_localhost_localhost_proto_enumTypes,
		MessageInfos:      file_github_com_moby_buildkit_session_localhost_localhost_proto_msgTypes,
	}.Build()
	File_github_com_moby_buildkit_session_localhost_localhost_proto = out.File
	file_github_com_moby_buildkit_session_localhost_localhost_proto_goTypes = nil
	file_github_com_moby_buildkit_session_localhost_localhost_proto_depIdxs = nil
}
