// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.11.4
// source: github.com/moby/buildkit/session/localhost/localhost.proto

package localhost

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Localhost_Exec_FullMethodName = "/moby.localhost.v1.Localhost/Exec"
	Localhost_Get_FullMethodName  = "/moby.localhost.v1.Localhost/Get"
	Localhost_Put_FullMethodName  = "/moby.localhost.v1.Localhost/Put"
)

// LocalhostClient is the client API for Localhost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Localhost is a service that allows for local execution on the client
type LocalhostClient interface {
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InputMessage, OutputMessage], error)
	// Get fetches a file or dir from the localhost and copies it to buildkit
	Get(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BytesMessage, BytesMessage], error)
	// Put sends a file or dir from buildkit and tells the localhost to save it locally
	Put(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BytesMessage, BytesMessage], error)
}

type localhostClient struct {
	cc grpc.ClientConnInterface
}

func NewLocalhostClient(cc grpc.ClientConnInterface) LocalhostClient {
	return &localhostClient{cc}
}

func (c *localhostClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InputMessage, OutputMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Localhost_ServiceDesc.Streams[0], Localhost_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InputMessage, OutputMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Localhost_ExecClient = grpc.BidiStreamingClient[InputMessage, OutputMessage]

func (c *localhostClient) Get(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BytesMessage, BytesMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Localhost_ServiceDesc.Streams[1], Localhost_Get_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BytesMessage, BytesMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Localhost_GetClient = grpc.BidiStreamingClient[BytesMessage, BytesMessage]

func (c *localhostClient) Put(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BytesMessage, BytesMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Localhost_ServiceDesc.Streams[2], Localhost_Put_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BytesMessage, BytesMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Localhost_PutClient = grpc.BidiStreamingClient[BytesMessage, BytesMessage]

// LocalhostServer is the server API for Localhost service.
// All implementations should embed UnimplementedLocalhostServer
// for forward compatibility.
//
// Localhost is a service that allows for local execution on the client
type LocalhostServer interface {
	Exec(grpc.BidiStreamingServer[InputMessage, OutputMessage]) error
	// Get fetches a file or dir from the localhost and copies it to buildkit
	Get(grpc.BidiStreamingServer[BytesMessage, BytesMessage]) error
	// Put sends a file or dir from buildkit and tells the localhost to save it locally
	Put(grpc.BidiStreamingServer[BytesMessage, BytesMessage]) error
}

// UnimplementedLocalhostServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocalhostServer struct{}

func (UnimplementedLocalhostServer) Exec(grpc.BidiStreamingServer[InputMessage, OutputMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedLocalhostServer) Get(grpc.BidiStreamingServer[BytesMessage, BytesMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedLocalhostServer) Put(grpc.BidiStreamingServer[BytesMessage, BytesMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedLocalhostServer) testEmbeddedByValue() {}

// UnsafeLocalhostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocalhostServer will
// result in compilation errors.
type UnsafeLocalhostServer interface {
	mustEmbedUnimplementedLocalhostServer()
}

func RegisterLocalhostServer(s grpc.ServiceRegistrar, srv LocalhostServer) {
	// If the following call pancis, it indicates UnimplementedLocalhostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Localhost_ServiceDesc, srv)
}

func _Localhost_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LocalhostServer).Exec(&grpc.GenericServerStream[InputMessage, OutputMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Localhost_ExecServer = grpc.BidiStreamingServer[InputMessage, OutputMessage]

func _Localhost_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LocalhostServer).Get(&grpc.GenericServerStream[BytesMessage, BytesMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Localhost_GetServer = grpc.BidiStreamingServer[BytesMessage, BytesMessage]

func _Localhost_Put_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LocalhostServer).Put(&grpc.GenericServerStream[BytesMessage, BytesMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Localhost_PutServer = grpc.BidiStreamingServer[BytesMessage, BytesMessage]

// Localhost_ServiceDesc is the grpc.ServiceDesc for Localhost service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Localhost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moby.localhost.v1.Localhost",
	HandlerType: (*LocalhostServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _Localhost_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Get",
			Handler:       _Localhost_Get_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Put",
			Handler:       _Localhost_Put_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "github.com/moby/buildkit/session/localhost/localhost.proto",
}
