// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.11.4
// source: github.com/moby/buildkit/api/services/registry/registry.proto

package earthly_registry_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ByteMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByteMessage) Reset() {
	*x = ByteMessage{}
	mi := &file_github_com_moby_buildkit_api_services_registry_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByteMessage) ProtoMessage() {}

func (x *ByteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_moby_buildkit_api_services_registry_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByteMessage.ProtoReflect.Descriptor instead.
func (*ByteMessage) Descriptor() ([]byte, []int) {
	return file_github_com_moby_buildkit_api_services_registry_registry_proto_rawDescGZIP(), []int{0}
}

func (x *ByteMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_github_com_moby_buildkit_api_services_registry_registry_proto protoreflect.FileDescriptor

const file_github_com_moby_buildkit_api_services_registry_registry_proto_rawDesc = "" +
	"\n" +
	"=github.com/moby/buildkit/api/services/registry/registry.proto\x12\x13earthly.registry.v1\"!\n" +
	"\vByteMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2[\n" +
	"\bRegistry\x12O\n" +
	"\x05Proxy\x12 .earthly.registry.v1.ByteMessage\x1a .earthly.registry.v1.ByteMessage(\x010\x01BDZBgithub.com/moby/buildkit/api/services/registry;earthly_registry_v1b\x06proto3"

var (
	file_github_com_moby_buildkit_api_services_registry_registry_proto_rawDescOnce sync.Once
	file_github_com_moby_buildkit_api_services_registry_registry_proto_rawDescData []byte
)

func file_github_com_moby_buildkit_api_services_registry_registry_proto_rawDescGZIP() []byte {
	file_github_com_moby_buildkit_api_services_registry_registry_proto_rawDescOnce.Do(func() {
		file_github_com_moby_buildkit_api_services_registry_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_moby_buildkit_api_services_registry_registry_proto_rawDesc), len(file_github_com_moby_buildkit_api_services_registry_registry_proto_rawDesc)))
	})
	return file_github_com_moby_buildkit_api_services_registry_registry_proto_rawDescData
}

var file_github_com_moby_buildkit_api_services_registry_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_moby_buildkit_api_services_registry_registry_proto_goTypes = []any{
	(*ByteMessage)(nil), // 0: earthly.registry.v1.ByteMessage
}
var file_github_com_moby_buildkit_api_services_registry_registry_proto_depIdxs = []int32{
	0, // 0: earthly.registry.v1.Registry.Proxy:input_type -> earthly.registry.v1.ByteMessage
	0, // 1: earthly.registry.v1.Registry.Proxy:output_type -> earthly.registry.v1.ByteMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_moby_buildkit_api_services_registry_registry_proto_init() }
func file_github_com_moby_buildkit_api_services_registry_registry_proto_init() {
	if File_github_com_moby_buildkit_api_services_registry_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_moby_buildkit_api_services_registry_registry_proto_rawDesc), len(file_github_com_moby_buildkit_api_services_registry_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_moby_buildkit_api_services_registry_registry_proto_goTypes,
		DependencyIndexes: file_github_com_moby_buildkit_api_services_registry_registry_proto_depIdxs,
		MessageInfos:      file_github_com_moby_buildkit_api_services_registry_registry_proto_msgTypes,
	}.Build()
	File_github_com_moby_buildkit_api_services_registry_registry_proto = out.File
	file_github_com_moby_buildkit_api_services_registry_registry_proto_goTypes = nil
	file_github_com_moby_buildkit_api_services_registry_registry_proto_depIdxs = nil
}
